uploads = []
generated = []

[[outputs]]
id = "pytwIk6kpbpW8X-IvJHZD"
uri = "file://artifacts/people-mobile/assets/screenshots/ss1-dashboard.png"
type = "image"
title = "Screenshot 1 — Dashboard"

[[outputs]]
id = "hytv05L2qTXjo33-8Nzih"
uri = "file://artifacts/people-mobile/assets/screenshots/ss2-add-person.png"
type = "image"
title = "Screenshot — Add Person (Marcus Webb, filled in)"

[[outputs]]
id = "WlzKLzzf0hei1enAVa1A4"
uri = "file://artifacts/people-mobile/assets/screenshots/ss3-profile.png"
type = "image"
title = "Screenshot — Profile View (Marcus Webb, big client)"

[[outputs]]
id = "W8etcDCpiiwAsO41vjLlG"
uri = "file://artifacts/people-mobile/assets/screenshots/ss5-tutorial.png"
type = "image"
title = "Screenshot 5 — Onboarding Tutorial"

[[outputs]]
id = "-QZ-ouXyent3QOmILO4cq"
uri = "file://artifacts/people-mobile/assets/images/splash-icon.png"
type = "image"
title = "Splash Screen Icon"

[[outputs]]
id = "LUMIIwk4Smmvc7nM_mnI4"
uri = "file://artifacts/people-mobile/assets/images/adaptive-icon.png"
type = "image"
title = "Android Adaptive Icon"
